import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  skill: [
    'skill/introduction',
  //   {
  //     type: 'category',
  //     label: '数据结构',
  //     // 这个目录文件在侧边栏点击的时候可以出现这个链接页面，若是autogenerated生成的目录会用_category_.yml来找到链接
  //     link: {
  //       type: 'generated-index',
  //       // 也可以是type: 'doc'
  //     }, 
  //     items: [
  //       {
  //         type: 'autogenerated',
  //         dirName: 'skill/data structure'
  //       }
  //     ],
  //   },
    //Python
    {
      type: 'category',
      label: 'Python',
      link: {
        type: 'generated-index',
        title: 'Python',
        // description: '根据官方文档学习的记录',
        keywords: ['Python']
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/programming-languages/python',
        }
      ]
    },
    // {
    //   type: 'category',
    //   label: '机器学习',
    //   link: {
    //     type: 'generated-index',
    //     title: '机器学习',
    //   },
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'skill/machine learning'
    //     }
    //   ]
    // },
    {
      type: 'category',
      label: '汇编语言',
      link: {
        type: 'generated-index',
        title: '汇编语言',
        // description: '根据官方文档学习的记录',
        keywords: ['汇编语言']
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/programming-languages/assembly_language',
        }
      ]
    },
    {
      type: 'category',
      label: 'LaTeX',
      link: {
        type: 'generated-index',
        title: 'LaTeX',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/LaTeX'
        }
      ]
    },
    {
      type:'category',
      label: '计算机网络',
      link:{
        type: 'generated-index',
        title: '计算机网络'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/computer network'
        }
      ]
    },
    {
      type:'category',
      label: '计算机系统基础',
      link:{
        type: 'generated-index',
        title: '计算机系统基础'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/computer_system_base'
        }
      ]
    },
    {
      type:'category',
      label: '算法',
      link:{
        type: 'generated-index',
        title: '算法'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/algorithm'
        }
      ]
    }
  ]
}

module.exports = sidebars
